#!/bin/sh

export COSMOPOLITAN_DISABLE_ZIPOS=1
export BASELOC=$(realpath "$PWD")
export COSMO=$BASELOC/cosmopolitan
export COSMOS_X86_64=$BASELOC/cosmos/x86_64
export COSMOS_AARCH64=$BASELOC/cosmos/aarch64
export RESULTS=$BASELOC/results
export ZIPCOPY=$COSMO/build/bootstrap/zipcopy.com
export APELINK=$COSMO/build/bootstrap/apelink.com
